// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_LOGGIN_IN_USER_REQUEST = 'GET_LOGGIN_IN_USER_REQUEST';
export const GET_LOGGIN_IN_USER_SUCCESS = 'GET_LOGGIN_IN_USER_SUCCESS';
export const GET_LOGGIN_IN_USER_ERROR = 'GET_LOGGIN_IN_USER_ERROR';

export const FETCH_RESTAURENT_REQUEST = 'FETCH_RESTAURENT_REQUEST';
export const FETCH_RESTAURENT_SUCCESS = 'FETCH_RESTAURENT_SUCCESS';
export const FETCH_RESTAURENT_ERROR = 'FETCH_RESTAURENT_ERROR';
